---
title: "Cyber_bird_data"
author: "Madeline Berger"
date: "2/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(reshape2)
library(paletteer)
library(janitor)
library(lubridate)
library(mgcv)


#read in our data
birds_all <- read_csv("UCSB_CampusLagoon_BirdSurveyData.csv") %>% 
  clean_names() %>% 
  select(species, lagoon_island_zone_summary, day:year)

#read in breeding bird survey data
bbs_all <- read_csv("bbs_data_all.csv") %>% 
  clean_names()
```

##Introduction: Description of Data and Project

The CCBER at UC Santa Barbara has been monitoring bird populations on and near campus since 1996. In 2005, the University began oak restoration...

###Data cleaning
```{r}

birds_all$species <- factor(birds_all$species)

#break out and then parse dates
data_long <- melt(birds_all,
        # ID variables - all the variables to keep but not split apart on
    id.vars=c("day", "month","year", "species"),
        # The source columns
    measure.vars=c("lagoon_island_zone_summary"),
        # Name of the destination column that will identify the original
        # column that the measurement came from
    variable.name="location",
    value.name="count"
) %>% 
  mutate(
    species = str_to_lower(species),
    date = paste(day, month, year),
    date = dmy(date)
  ) %>% 
  dplyr::select(-month, -day) %>% 
  mutate(
    month = month(date, label = FALSE)
  ) %>% 
  mutate(species = case_when(
    species %in% "western scrub-jay" ~ "california scrub-jay",
    TRUE ~ species
  ))

#if we want each line to represent one bird, also change the name of the scrub jay to match bbs
data_tidy<- uncount(data_long, weights = count) %>% 
  mutate(species = str_to_lower(species)) %>% 
  mutate(species = case_when(
    species %in% "western scrub-jay" ~ "california scrub-jay",
    TRUE ~ species
  ))


#filter by the species we are interested in, and up to 2016 since that is what best matches the bbs 

#tidy version (missing zero counts)
bird_species_tidy <- data_tidy %>% 
  filter(species == "california scrub-jay" | species =="common yellowthroat"| species == "song sparrow" | species == "bewick's wren" | species == "white-crowned sparrow" | species == "house finch" | species == "california towhee" | species == "blue-gray gnatcatcher")

#version with counts
bird_species_count <- data_long %>% 
  filter(species == "california scrub-jay" | species =="common yellowthroat"| species == "song sparrow" | species == "bewick's wren" | species == "white-crowned sparrow" | species == "house finch" | species == "california towhee" | species == "blue-gray gnatcatcher")




```


##Summary graphs

```{r}

#create df that summarize yearly and monthly totals
bird_summary_year <- bird_species_tidy %>% 
  select(-location) %>%
  filter(species != "house finch") %>% 
  group_by(year, species) %>% 
  summarize(
    count = length(species)
  )

bird_summary_month <- bird_species_tidy %>% 
  select(-location) %>% 
  group_by(month, species) %>% 
  summarize(
    count = length(species)
  )


finch_sparrow_only <- bird_species_tidy %>% 
  select(-location) %>% 
  filter(species == "song sparrow" | species == "house finch") %>% 
  group_by(year, species) %>% 
  summarize(
    count = length(species)
  )

#graph minus house finch
yearly_abundance_graph <- ggplot(bird_summary_year, aes(x = year, y = count, group = species))+ 
  geom_line(aes(color = species))+
  theme_minimal()+
  labs(x = "Year", y = "Count", title = "Yearly passerine count at  Lagoon Island 1996 - 2017")+
  scale_y_continuous(expand = c(0,0))+
  geom_vline(xintercept = 2005, linetype = "dashed")

yearly_abundance_graph

yearly_abundance_graph +
  scale_color_paletteer_d("calecopal::figmtn")


#just sparrow and finch 

sparrow_finch_gg <- ggplot(finch_sparrow_only, aes(x = year, y = count, group = species)) +
  geom_line(aes(color = species))+
  theme_minimal()+
  labs(x = "Year", y = "Count", title = "Yearly house finch and song sparrow count at  Lagoon Island 1996 - 2017")+
  scale_y_continuous(expand = c(0,0))+
  geom_vline(xintercept = 2005, linetype = "dashed")+
  scale_color_paletteer_d("calecopal::lake")
  
sparrow_finch_gg


#by month

monthy_ab_graph <- ggplot(bird_summary_month, aes(x = month, y = count, group = species))+ 
  geom_line(aes(color = species))+
  theme_minimal()+
  labs(x = "Month", y = "Count", title = "Monthly passerine count at Lagoon Island 1996 - 2017")+
  scale_y_continuous(expand = c(0,0))

monthy_ab_graph



```

Exporting Graphs
```{r}
png("graph_1.png", units = "in", width = 6, height = 3, res = 300)

ggplot(bird_summary_year, aes(x = year, y = count, group = species))+ 
  geom_line(aes(color = species))+
  theme_minimal()+
  labs(x = "Year", y = "Count", title = "Yearly passerine count at  Lagoon Island 1996 - 2017")+
  scale_y_continuous(expand = c(0,0)) +
  geom_vline(xintercept = 2005)


```


##Analysis

###CCBER data
```{r}
#go back to count
#pick a species

birds_all_sparrow <- birds_all %>% 
  filter(species == "Song Sparrow")

#run GAM on CCBER data 
ccber_model <- mgcv::gam(lagoon_island_zone_summary ~ year, family = poisson, data = birds_all_sparrow)

summary(ccber_model)

#create new data frame to use with the model
newd <- data.frame(year = 1996:2016)

#predict abundance using new data

bird_predict <- predict.gam(ccber_model, newd)

bird_predict

#notes /issues
#didn't month because I couldn't figure it out
#how can we ask the models for integers

```


